---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://docs.ansible.com/ansible/latest/modules/lxd_container_module.html

# Prune container settings after completion of test work

- name: Prune SSH host key entries
  hosts: all
  connection: local
  gather_facts: yes

  # Likely needed to avoid race conditions (refs atc0005/ansible-playbooks#11)
  serial: 1

  # TODO: Cleanup, move to defaults/main.yml when migrating to lxd-testenv role
  vars_files:
    - vars/main.yml

  tasks:

    # Note: If setting 'hosts' for this play to anything but localhost, make
    # sure to set 'serial: 1' in order to avoid race conditions
    # (refs atc0005/ansible-playbooks#11)
    - name: "Remove container hostkeys from known_hosts file on LXD host via IP Address"
      become: no
      delegate_to: localhost
      known_hosts:
        path: "{{ ssh_known_hosts_file }}"
        name: "{{ ansible_default_ipv4.address }}"
        state: absent
      tags:
        - remove

    - name: "Remove container hostkeys from known_hosts file on LXD host via hostname"
      delegate_to: localhost
      become: no
      known_hosts:
        path: "{{ ssh_known_hosts_file }}"
        name: "{{ inventory_hostname }}"
        state: absent
      tags:
        - remove

    - name: "Remove container entries from hosts file on LXD host"
      delegate_to:
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ inventory_hostname }}$'
        state: absent
      tags:
        - remove

- name: Remove our LXD containers
  hosts: all
  connection: local
  gather_facts: no

  # TODO: Cleanup, move to defaults/main.yml when migrating to lxd-testenv role
  vars_files:
    - vars/main.yml

  tasks:

    - name: Stop containers
      delegate_to: localhost
      lxd_container:
        name: "{{ inventory_hostname }}"
        state: stopped
        timeout: 90
      tags:
        - remove

    - name: Delete containers
      delegate_to: localhost
      lxd_container:
        name: "{{ inventory_hostname }}"
        state: absent
        timeout: 90
      tags:
        - remove

...
