---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://docs.ansible.com/ansible/latest/modules/lxd_container_module.html

# Prune container settings after completion of test work

- name: Tear down our LXD test environment
  hosts: all
  connection: local
  gather_facts: no

  # This is needed due to potential for multiple access attempts via modules
  # that are not intended/designed for it. Without this setting occasional
  # race conditions occur which results in data corruption.
  serial: 1

  tasks:

    - name: Apply lxd-testenv role
      import_role:
        name: atc0005.lxd-testenv
      vars:
        # Valid values: "create" and "remove"
        state: "remove"
        lxd_host_remove_container_settings: true
        lxd_host_remove_containers: true



...
