---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://docs.ansible.com/ansible/latest/modules/lxd_container_module.html

# An example for creating Ubuntu containers and installing python in each

- name: Update container host
  hosts: all
  connection: local
  gather_facts: no

  # Likely needed to avoid race conditions (refs atc0005/ansible-playbooks#11)
  serial: 1

  # TODO: Cleanup, move to defaults/main.yml when migrating to lxd-testenv role
  vars_files:
    - vars/main.yml

  tasks:

    # https://groups.google.com/forum/#!topic/Ansible-project/n5bYP5BIbcQ
    - name: Gather facts
      setup:
      become: no
      # Any special meaning for this variable name?
      register: setup

    # Generate /etc/hosts with Ansible
    # https://gist.github.com/rothgar/8793800
    - name: "Update hosts file on LXD host"
      become: yes
      delegate_to: localhost
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ inventory_hostname }}$'
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
        state: present
      when:
        - ansible_default_ipv4.address is defined
        - update_host_etc_hosts_file

    # https://stackoverflow.com/questions/30226113/ansible-ssh-prompt-known-hosts-issue
    - name: Scan each host for its ssh public key
      become: no
      # If hashed entries are desired, use the '-H' option:
      #ssh-keyscan -H {{ inventory_hostname }},{{ ansible_default_ipv4.address }}
      shell: |
        ssh-keyscan {{ inventory_hostname }},{{ ansible_default_ipv4.address }}
      register: ssh_known_host_results
      delegate_to: localhost
      delegate_facts: yes
      changed_when: ssh_known_host_results.rc != 0
      failed_when: ssh_known_host_results.rc != 0
      when:
        - ansible_default_ipv4.address is defined
        - update_host_known_hosts_file

    # - name: Display ssh host key results
    #   debug:
    #     var: ssh_known_host_results

    - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
      delegate_to: localhost
      known_hosts:
        name: "{{ inventory_hostname }}"
        key: "{{ ssh_known_host_results.stdout }}"
        path: "{{ ssh_known_hosts_file }}"
      when:
        - update_host_known_hosts_file
      with_items: "{{ ssh_known_host_results.stdout_lines }}"

# "{{ hostvars[inventory_hostname]['source'] }}"
